// packages/lit-ranger/src/index.ts
import { ReactiveController, ReactiveControllerHost } from 'lit'
import { Ranger, RangerConfig, RangerOptions } from '@tanstack/ranger'

export * from '@tanstack/ranger'

export class RangerController<TTrackElement> implements ReactiveController {
  host: ReactiveControllerHost

  private ranger: Ranger<TTrackElement> | null = null

  constructor(host: ReactiveControllerHost) {
    ;(this.host = host).addController(this)
  }

  private async rerender() {
    await this.host.updateComplete
    this.host.requestUpdate()
  }

  getRanger(options: RangerOptions<TTrackElement>) {
    const resolvedOptions: RangerConfig<TTrackElement> = {
      ...options,
      rerender: async () => {
        await this.rerender()
      },
      onChange: async (instance) => {
        await this.rerender()
        options.onChange?.(instance)
      },
    }

    if (!this.ranger) {
      this.ranger = new Ranger<TTrackElement>(resolvedOptions)
    }
    this.ranger.setOptions(resolvedOptions)
    return this.ranger
  }

  async hostUpdated() {
    this.ranger?._willUpdate()
  }
}

// packages/react-ranger/src/index.tsx
import * as React from 'react'
import { RangerConfig, RangerOptions, Ranger } from '@tanstack/ranger'

export * from '@tanstack/ranger'

const useIsomorphicLayoutEffect =
  typeof window !== 'undefined' ? React.useLayoutEffect : React.useEffect

export function useRanger<TTrackElement>(
  options: RangerOptions<TTrackElement>,
): Ranger<TTrackElement> {
  const rerender = React.useReducer(() => ({}), {})[1]
  const resolvedOptions: RangerConfig<TTrackElement> = {
    ...options,
    rerender: rerender,
    onChange: (instance) => {
      rerender()
      options.onChange?.(instance)
    },
  }

  const [instance] = React.useState(
    () => new Ranger<TTrackElement>(resolvedOptions),
  )

  instance.setOptions(resolvedOptions)

  useIsomorphicLayoutEffect(() => {
    return instance._willUpdate()
  })

  return instance
}

export type { Ranger }
